version: "3"
services:
  web:
    # 使用你自己的username/repo:tag
    image: marksinoberg/ipservice:v3
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: